Lesson 2
kokdot/qna pull request #1
Opened 2020-09-03 08:26 UTC by kokdot

2020-09-03 09:24 UTC, vkurennov requested changes

2020-09-03 09:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question , notice: "Body can't be blank"
нельзя делать редирект при ошибках валидации, их может быть больше одной и нужно рендерить страницу вопроса и там выводить ошибки через модель

2020-09-03 09:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def create
пустые строки перед методами

2020-09-03 09:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def destroy
по заданию, тут нужно проверять, что текущий пользователь - автор. даже если такая проверка есть в видах, т.к. легко сделать прямой запроса

2020-09-03 09:24 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def index
пустая строка

2020-09-03 09:24 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.user_id = current_user.id
присваивать лучше по ассоциациям и объектам, а вот сравнивать - по id

2020-09-03 09:24 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def destroy
тут должна быть провекра на автора

2020-09-03 09:24 UTC, vkurennov commented on app/models/answer.rb
> +
перед  end никогда не ставится пустая строка, ни в классах, ни в методах, ни в блоках

2020-09-03 09:24 UTC, vkurennov commented on app/views/layouts/application.html.slim
> +    p= link_to 'Log Out', destroy_user_session_path, method: :delete
хорошо бы еще и ссылку на вход показать для незалогиненного юзера

2020-09-03 09:24 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      = render 'shared/errors', resource: answer
зачем в списке выводить ошибки? ошибки возможно только для одного, создаваемого ответа. но зачем невалидный ответ вообще в списке выводить?

2020-09-03 09:24 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      p= link_to 'Destroy', answer, method: :delete, local: true
ссылку на удаление надо показывать только автору ответа

2020-09-03 09:24 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if @question.user == current_user
сравнивать как раз нужно по user_id, чтобы не делать лишний запрос. и т.к. эта проверка нужна будет еще не раз, стоит вынести ее в метод модели User и вызывать там, где такая проверка понадобится (и не забудьте тесты на этот метод написать в спеках модели)

2020-09-03 09:24 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +RSpec.describe AnswersController, type: :controller do
где тесты на destroy?

2020-09-03 09:24 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
здесь нужно проверить что ответ связывается с вопросом и с залогиненным юзером (2 разных теста)

2020-09-03 09:24 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
здесь надо проверить, что создаваемый вопрос связывается с залогиненным юзером

2020-09-03 09:24 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +    scenario 'destroy answer for the question' do
тут еще 2 сценанрия должно быть: один для не-автора и для незалогиненного юзера

2020-09-03 09:24 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +      expect(page).to have_content 'Your question successfully destroyed.'
надо проверить, что вопроса больше нет на странице

2020-09-03 12:37 UTC, kokdot commented on app/controllers/answers_controller.rb
> +      redirect_to @question , notice: "Body can't be blank"
есть

2020-09-03 13:09 UTC, kokdot commented on app/controllers/answers_controller.rb
> +  def destroy
есть

2020-09-03 13:10 UTC, kokdot commented on app/controllers/questions_controller.rb
> +  def index
есть

2020-09-03 13:14 UTC, kokdot commented on app/controllers/questions_controller.rb
> +    @question.user_id = current_user.id
есть

2020-09-03 13:24 UTC, kokdot commented on app/views/layouts/application.html.slim
> +    p= link_to 'Log Out', destroy_user_session_path, method: :delete
есть

2020-09-03 14:24 UTC, kokdot commented on app/views/questions/show.html.slim
> +      = render 'shared/errors', resource: answer
есть

2020-09-04 06:11 UTC, kokdot commented on spec/controllers/answers_controller_spec.rb
> +RSpec.describe AnswersController, type: :controller do
есть

2020-09-04 06:23 UTC, kokdot commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
есть

2020-09-04 06:26 UTC, kokdot commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
есть

2020-09-04 07:03 UTC, kokdot commented on spec/features/answer/destroy_spec.rb
> +    scenario 'destroy answer for the question' do
есть

2020-09-04 07:06 UTC, kokdot commented on spec/features/question/destroy_spec.rb
> +      expect(page).to have_content 'Your question successfully destroyed.'
есть

2020-09-04 07:07 UTC, kokdot commented on app/controllers/answers_controller.rb
> +  def create
есть

2020-09-04 08:11 UTC, vkurennov requested changes

2020-09-04 08:11 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        p= link_to 'Destroy', "/answers/#{answer.id}", method: :delete, local: true
ну через интерполяцию пути задавать - очень некрасиво. есть же url-хелперы. тут можно было оставить тот же answer, как и было ранее, зачем было менять?

2020-09-04 08:11 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if @question.user == current_user
это надо заменить на вызов метода User#author_of?

2020-09-04 08:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  context 'Your answer' do
только наоборот должно быть: на каждый экшн свой describe, а в нем уже разные контексты (потому что сначала **описываем** что-то, а внутри уже задаем контексты для этого чего-то).

2020-09-04 08:11 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    describe 'DELETE #destroy' do
тут чисто логически даже видно дублирование describ'ов, а дублирование - это плохо. поэтому как раз делаем один describe для destroy и в нем контекты для автора и для не автора

2020-09-04 08:11 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  context 'Your question' do
то же самое, что для ответов - один describe для экшена, внутри разные контексты. Посмотрите, например, на тесты для create, там ровно так сделано. контексты вкладываются в describe, не наоборот

2020-09-04 08:11 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
я же сразу писал - не забудьте тесты на метод `autho_of?` )) в итоге - забыли, надо дописать

2020-09-04 09:59 UTC, kokdot commented on app/views/questions/show.html.slim
> +        p= link_to 'Destroy', "/answers/#{answer.id}", method: :delete, local: true
есть

2020-09-04 10:04 UTC, kokdot commented on spec/controllers/answers_controller_spec.rb
> +  context 'Your answer' do
есть

2020-09-04 10:04 UTC, kokdot commented on spec/controllers/answers_controller_spec.rb
> +    describe 'DELETE #destroy' do
есть

2020-09-04 10:06 UTC, kokdot commented on spec/controllers/questions_controller_spec.rb
> +  context 'Your question' do
есть

2020-09-04 10:09 UTC, kokdot commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
есть

2020-09-05 08:50 UTC, merged