Lesson 6
kokdot/qna pull request #2
Opened 2020-09-10 14:18 UTC by kokdot

Lesson 6

2020-09-11 10:20 UTC, vkurennov requested changes

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @number = 1
Это что за магическое число?

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      @answer.user_id = current_user.id
присваивать лучше по объектам, а сравнивать - по id

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def best
не нужно бизнес-логику реализовывать в контроллере, это не его ответсвенность. есть такой принцип "тонкие контроллеры - толстые модели", который как раз и говорит, что вся логика должна бытьв моделях, а здесь лишь вызываются нужные методы. поэтому все логику назначения лучшего ответа надо вынести в модель и здесь вызвать метод модели

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answers.each do |answer|
здесь можно использовать метод update_all, чтобы за один запрос изменить нужные записи

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      answer.best = 'a'
здесь идеально подходит boolean-атрибут, все же строковые типы нужны, когда может быть записана произвольная строка. а так true/false четко и понятно.

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.best = 'b'
если нужно записать атрибут (атрибуты) и одновременно их сохранить, стоит использовать метод update

2020-09-11 10:20 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      - @number += 1
если нужен подсчет в цикле, то не нужно это делать через инстанс-переменные в контроллере, иначе, это все размазывается по коду и непонятно как этим управлять. В этом случае стоит использовать цикл для вывода ответов через `each_with_index`

2020-09-11 10:20 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - @answers.each do |ans|
если здесь использовать each_with_index, то отпадет необходимость в @number, который очень загрязняе код

2020-09-11 10:20 UTC, vkurennov commented on config/routes.rb
> +        get 'best'
get-запросы не должны изменять данные, это грубое нарушение принципов REST. только post/patch/put/delete-запросы могут менять данные, get - только поулчат их.

2020-09-11 10:20 UTC, vkurennov commented on db/migrate/20200909113236_add_best_to_answers.rb
> +    add_column :answers, :best, :boolean
ну вот было же верно, зачем менять это на строку? какой в этом смысл?

2020-09-11 10:20 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'answer belongs to user' do
описания и суть теста не совпадают, здесь проверяется связь с вопросом, а в описании - user, в предыдущем тесте - наоборот

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def update
по заданию, только автор может менять ответ, т.е. здесь нужна проверка на автора, такая же как в destroy

2020-09-11 10:20 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def update
в контроллере вопросов тоже надо добавить проверку на автора в update и в тестах контроллера соответсвенно сделать 2 контекста - для автора и для не-автора

2020-09-11 10:20 UTC, vkurennov commented on db/migrate/20200909131304_add_best1_to_answers.rb
> +class AddBest1ToAnswers < ActiveRecord::Migration[5.2]
на будущее: в рамках одной задачи, пока она еще не слита, не стоит плодить миграции, если нужно что-то изменить, лучше откатит миграцию и поменять ее. а вот когда уже все попало в основной репозиторий, так делать уже нельзя, конечно.

2020-09-11 10:20 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #update' do
тут должно быть еще 2 контекста: для автора и для не-автора

2020-09-18 09:12 UTC, kokdot commented on app/controllers/answers_controller.rb
>      @answer.user_id = current_user.id
есть

2020-09-18 11:50 UTC, kokdot commented on app/controllers/answers_controller.rb
> +  def best
Есть

2020-09-18 12:16 UTC, kokdot commented on app/controllers/answers_controller.rb
> +    @answers.each do |answer|
есть

2020-09-18 12:48 UTC, kokdot commented on app/controllers/answers_controller.rb
> +      answer.best = 'a'
есть

2020-09-18 12:48 UTC, kokdot commented on db/migrate/20200909113236_add_best_to_answers.rb
> +    add_column :answers, :best, :boolean
есть

2020-09-18 12:50 UTC, kokdot commented on spec/controllers/answers_controller_spec.rb
>        it 'answer belongs to user' do
есть

2020-09-18 15:25 UTC, kokdot commented on app/controllers/answers_controller.rb
> +  def update
есть

2020-09-18 15:25 UTC, kokdot commented on db/migrate/20200909131304_add_best1_to_answers.rb
> +class AddBest1ToAnswers < ActiveRecord::Migration[5.2]
есть

2020-09-18 15:46 UTC, vkurennov requested changes

2020-09-18 15:46 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @number = 1
этот комментарий означал, что нужно избавиться от этих переменных, как - описывалось дальше

2020-09-18 15:46 UTC, vkurennov commented on app/models/answer.rb
> +    @question = self.question
зачем здесь инстанс-переменная?

2020-09-18 15:46 UTC, vkurennov commented on app/models/answer.rb
> +    self.best = true
это заменяется на  `update(best: true)`

2020-09-18 15:46 UTC, vkurennov commented on app/models/answer.rb
> +    Answer.where(question_id: @question).order(best: :desc)
`question.answers.order`, но вообще, не стоит отсюда возвращать список. лучше метод просто будет назначать лучший ответ, а в видах можно вызвать скоуп, который уже и вернет отсортированный список

2020-09-18 15:46 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      - @number += 1
не исправлено

2020-09-18 15:46 UTC, vkurennov commented on app/models/answer.rb
> +    self.best = true
и раз тут несколько апдейтов, то их нужно обернуть в [транзакцию](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)

2020-09-18 15:46 UTC, vkurennov commented on app/models/answer.rb
> +  def best_assign
А где тесты модели на этот метод? Если в модели (или другом классе) есть какой-то код, то должны быть соответсвующие для него тесты

2020-09-19 06:57 UTC, kokdot commented on app/models/answer.rb
> +    @question = self.question
есть

2020-09-19 07:21 UTC, kokdot commented on app/models/answer.rb
> +    self.best = true
есть

2020-09-19 09:01 UTC, kokdot commented on app/models/answer.rb
> +    Answer.where(question_id: @question).order(best: :desc)
есть

2020-09-19 12:04 UTC, kokdot commented on app/models/answer.rb
> +  def best_assign
есть

2020-09-19 15:01 UTC, vkurennov requested changes

2020-09-19 15:01 UTC, vkurennov commented on app/models/answer.rb
> +      update(best: true)
внутри транзакций надо испиользовать bang-версии методов, т.е. здесь должен быть `update!`, т.к. транзакция откатывается только при исключениях

2020-09-19 15:01 UTC, vkurennov commented on app/models/answer.rb
> +  scope :best_order, ->(question) { where(question_id: question).order(best: :desc) }
скоупы принято в моделях указывать до методов

2020-09-19 15:01 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    it 'assign the best for answer' do
этот тест как-то очень слабо проверяет работу метода. Здесь должно быть 2 теста:
1) проверяем, что у ответа, у которого вызван метод, свойство меняется в true
2) создаем заранее лучший ответ, а затем у другого ответа вызыаем метод, проверяем, что у первого флаг снят.

2020-09-21 06:35 UTC, kokdot commented on app/models/answer.rb
> +      update(best: true)
есть

2020-09-21 06:36 UTC, kokdot commented on app/models/answer.rb
> +  scope :best_order, ->(question) { where(question_id: question).order(best: :desc) }
есть

2020-09-21 07:24 UTC, kokdot commented on spec/models/answer_spec.rb
> +    it 'assign the best for answer' do
есть

2020-09-21 08:04 UTC, vkurennov requested changes

2020-09-21 08:04 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.best).to_not be_falsy
лучше так: `expect(answer).to be_best`

2020-09-21 08:04 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.best_assign
у нас по заданию условие, что только автор вопроса это может сделать. нужна проверка на это в контроллере

2020-09-21 08:33 UTC, vkurennov approved these changes

2020-09-21 08:33 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @number = 0
вот еще @number остался

2020-09-21 08:33 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - @number = 1
и вот по-прежнему @number

2020-09-21 08:33 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = render ans, object: @number
и тут передается

2020-09-21 08:47 UTC, merged