lesson_9
kokdot/qna pull request #5
Opened 2020-10-22 14:21 UTC by kokdot

lesson_9

2020-10-22 20:51 UTC, IvanShamatov requested changes
В двух моделях есть по ассоциации has_many :votes и будет по методу rating
Пусть хотя бы это уйдет в консерн.

Сейчас, если спеки в ансверах и проходят, то это потому что не проверяется, изменения рейтинга

2020-10-22 20:51 UTC, IvanShamatov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.where(user_id: current_user, votable_id: @votable).first
неа, так не пойдет. `Vote.find_by(user: current_user, votable: @votable)` вот так правильно. Ато ты получишь на свой запрос любой голос за вне зависимости от типа.

2020-10-22 20:51 UTC, IvanShamatov commented on app/controllers/votes_controller.rb
> +      @votable = Question.find(params[:id])
вообще votable как мы делали с @answer или с @question можно находить в before_action'e

2020-10-22 20:51 UTC, IvanShamatov commented on app/controllers/votes_controller.rb
> +        @vote = Vote.new
`@vote = @votable.votes.new(votes: 1, user: current_user)`

2020-10-22 20:51 UTC, IvanShamatov commented on app/controllers/votes_controller.rb
> +          format.json { render json: {sum: Question.rating(@votable)} }
почему тут речь про рейтинг через скоуп вопроса?

2020-10-22 20:51 UTC, IvanShamatov commented on app/models/vote.rb
> +  validates :votes, presence: true
очень плохое название для  поля со значением в почти одноименной модели. Плюс оно путается с votes ассоциацией. лучше использовать value

2020-10-22 20:51 UTC, IvanShamatov commented on app/models/question.rb
> +  scope :rating, ->(question) { Vote.where(votable_id: question).inject (0) { |sum, vote| sum + vote.votes} }
плохое решение. 
Во-первых, это вовсе не скоуп, если он возвращает значение, а не релейшн.
Во-вторых, можно использовать специальный метод sum, который сделает сумму средствами базы данных

где-то, где доступна ассоциация votes:

```ruby
def rating
  votes.sum(:value)
end
```

и тогда в месте.  где нужно отрисовать рейтинг, просто использовать @votable.rating

2020-10-22 20:51 UTC, IvanShamatov commented on app/views/votes/destroy.html.slim
> +h1 Votes#destroy
лишняя какая-то шляпа

2020-10-22 20:51 UTC, IvanShamatov commented on config/routes.rb
> +  # resources :votes do
правильная задумка, могла бы быть выполнена как-то так
```ruby
resources :votes, only: [] do
  collection do
    post 'up'
    post 'down'
    post 'cancel'
  end
end
```

2020-10-22 20:51 UTC, IvanShamatov commented on app/controllers/votes_controller.rb
> +  # def create
Понятно замешательство. 
В этом есть смысл. 
Если мы оперируем нерестфульными экшенами up/down/cancel, то ими было логично расширить два уже имеющихся контроллера. 
Если же мы говорим про отдельный контроллер, то create/update это про up/down, а cancel про destroy.

Оба варианта приемлемы. Выбери, какой ближе.

2020-10-23 09:43 UTC, kokdot commented on app/controllers/votes_controller.rb
> +    @vote = Vote.where(user_id: current_user, votable_id: @votable).first
есть

2020-10-23 09:49 UTC, kokdot commented on app/controllers/votes_controller.rb
> +      @votable = Question.find(params[:id])
есть

2020-10-23 12:16 UTC, kokdot commented on app/controllers/votes_controller.rb
> +        @vote = Vote.new
есть

2020-10-23 12:18 UTC, kokdot commented on app/models/vote.rb
> +  validates :votes, presence: true
есть

2020-10-23 12:50 UTC, kokdot commented on app/models/question.rb
> +  scope :rating, ->(question) { Vote.where(votable_id: question).inject (0) { |sum, vote| sum + vote.votes} }
есть

2020-10-23 12:51 UTC, kokdot commented on app/views/votes/destroy.html.slim
> +h1 Votes#destroy
есть

2020-10-23 13:00 UTC, kokdot commented on app/controllers/votes_controller.rb
> +          format.json { render json: {sum: Question.rating(@votable)} }
есть

2020-11-22 12:26 UTC, merged