Lesson 11
kokdot/qna pull request #7
Opened 2020-12-08 14:45 UTC by kokdot

Lesson 11

2020-12-08 21:11 UTC, IvanShamatov requested changes

2020-12-08 21:11 UTC, IvanShamatov commented on app/controllers/oauth_callbacks_controller.rb
> +    @auth = request.env['omniauth.auth']
если эта переменная нигде не используется во вьюшке, то нет смысла создавать инстанс-переменную. Локальной будет достаточно

2020-12-08 21:11 UTC, IvanShamatov commented on app/controllers/oauth_callbacks_controller.rb
> +    @user = User.find_for_oauth(@auth)
оборачивать сервис в метод класса Юзер нет смысла, лучше вызвать сервис напрямую и уменьшить связность с классом. Видимо ролику года 3-4, так сейчас уже не пишут

2020-12-08 21:11 UTC, IvanShamatov commented on app/controllers/oauth_callbacks_controller.rb
> +    elsif @auth != :invalid_credential && @auth != nil
тут лучше проверить, что если в auth нет емейла

2020-12-08 21:11 UTC, IvanShamatov commented on app/controllers/oauth_callbacks_controller.rb
> +      session[:auth] = @auth
так можно, но в @auth может лежать очень много лишней информации, поскольку из всего этого хеша нам нужны только uid и provider, то рекомендую в сессию сохранить исключительно их.

2020-12-08 21:11 UTC, IvanShamatov commented on app/controllers/oauth_callbacks_controller.rb
> +      @user = User.new
тут нет смысла создавать инстанс юзера, если мы после этого делаем редирект. вместо редиректа можно было бы здесь сделать render той вьюшки, где форма для email'a, ну или юзера не делать, а сразу редиректнуть

2020-12-08 21:11 UTC, IvanShamatov commented on app/controllers/users_controller.rb
> +    @user.authorizations.create(provider: auth['provider'], uid: auth['uid'])
тут все ок, но после создания авторизации хорошо бы обнулить ненужные вещи из сессии
session[:auth] = nil

2020-12-08 21:11 UTC, IvanShamatov commented on app/models/user.rb
> +  TEMP_EMAIL_REGEX = /\Achange@me/
похоже что-то забыто

2020-12-08 21:11 UTC, IvanShamatov commented on app/models/user.rb
> +  def create_authorization(auth)
этот метод нужен в рамках сервиса, туда его и стоит поместить.

2020-12-08 21:11 UTC, IvanShamatov commented on app/models/user.rb
> +  def email_verified?
вообще-то verified? означает несколько другое, а тут разве что проверка на валидность

2020-12-08 21:11 UTC, IvanShamatov commented on app/services/find_for_oauth.rb
> +    user = User.where(email: email).first if email
where...first меняются на find_by(email: email)

2020-12-09 07:06 UTC, kokdot commented on app/controllers/oauth_callbacks_controller.rb
> +    @auth = request.env['omniauth.auth']
есть

2020-12-09 07:33 UTC, kokdot commented on app/controllers/oauth_callbacks_controller.rb
> +      session[:auth] = @auth
Есть

2020-12-09 07:48 UTC, kokdot commented on app/controllers/oauth_callbacks_controller.rb
> +      @user = User.new
Понял

2020-12-09 07:51 UTC, kokdot commented on app/controllers/users_controller.rb
> +    @user.authorizations.create(provider: auth['provider'], uid: auth['uid'])
есть

2020-12-09 07:52 UTC, kokdot commented on app/models/user.rb
> +  def create_authorization(auth)
есть

2020-12-09 07:52 UTC, kokdot commented on app/models/user.rb
> +  def email_verified?
есть

2020-12-09 07:52 UTC, kokdot commented on app/models/user.rb
> +  TEMP_EMAIL_REGEX = /\Achange@me/
есть

2020-12-09 07:55 UTC, kokdot commented on app/services/find_for_oauth.rb
> +    user = User.where(email: email).first if email
есть

2020-12-09 07:56 UTC, kokdot commented on app/controllers/oauth_callbacks_controller.rb
> +    elsif @auth != :invalid_credential && @auth != nil
Это не так просто. Получается еще больше проверок и вообще не хочет работать.
 Вобщем я пробовал но чето не получилась проверить на присутствие email.

2020-12-09 11:52 UTC, IvanShamatov commented on app/models/user.rb
> +  def create_authorization(auth)
а отсюда убрать...

2020-12-09 11:53 UTC, IvanShamatov approved these changes

2020-12-09 11:53 UTC, IvanShamatov commented on app/services/find_for_oauth.rb
> +    self.authorizations.create(provider: auth.provider, uid: auth.uid)
идея была в том, чтобы убрать метод из модели и поместить сюда

```ruby
def create_authorization(user, auth)
    user.authorizations.create(provider: auth.provider, uid: auth.uid) 
end
```

2020-12-09 12:00 UTC, kokdot commented on app/services/find_for_oauth.rb
> +    self.authorizations.create(provider: auth.provider, uid: auth.uid)
Понял

2020-12-09 12:13 UTC, kokdot commented on app/controllers/oauth_callbacks_controller.rb
> +    @user = User.find_for_oauth(@auth)
Так у Виталия в скринкасте. Он показывал как это в принципе возможно.

2020-12-09 12:14 UTC, merged